### PR TITLE
Handling of overcurrent flag

### PR DESCRIPTION
**Pull request by pattacini**
This PR addresses #58 by adding up the transmission of the overcurrent flag via CAN.

Here's a list of things I did:

#### 🔘 Updated `Flags` in the dictionary

image

#### 🔘 Updated `SupervisorRX` FSM

image

#### 🔘 Updated `SupervisorTX/MSG_STATUS_HANDLER` FSM

image

#### 🔘 Updated `CAN_Encoder/STATUS/format_status_pck` function

```matlab
function pl = format_status_pck(control_mode, pwm_fbk, flags, shift, CAN_VOLT_REF_SHIFT)

pl = uint8((zeros(8, 1)));

pl(1) = uint8(control_mode);

pl(2) = uint8(0);

tmp1 = bitshift(pwm_fbk, CAN_VOLT_REF_SHIFT - shift);
tmp2 = typecast(tmp1, 'uint8');
pl(3) = tmp2(1);
pl(4) = tmp2(2);

% See https://github.com/robotology/icub-firmware/blob/devel/emBODY/eBcode/arch-arm/board/amc2c/bsp/motorhal/motorhal_faults.h
pl(5) = bitset(pl(5), 1, flags.ExternalFaultAsserted);
pl(5) = bitset(pl(5), 4, flags.OverCurrentFailure);
pl(6) = uint8(0);
pl(7) = uint8(0);
pl(8) = uint8(0);
```

### 📝 AOB

> [!warning]
I also had to update some test models (see the tab <kbd>Files changed</kbd>) to comply with the changes in the dictionary.

> [!note]
@mfussi66, we're required to port these modifications to the new architectural model.

### ⚙️ Tests

> [!important]
The changes need to be tested!

---

cc @valegagge @Nicogene @mfussi66 @sgiraz

### CODE REVIEW

**Comment by pattacini** [comment]
We need to finalize the test of this PR within this week.
cc @sgiraz @Nicogene

**Comment by sgiraz** [comment]
Hi @pattacini,

I'm going to test this features in the next few hours , stay tuned! 📢

cc @Nicogene

**Comment by sgiraz** [comment]
Hi @pattacini,

Here are the results promised:

https://github.com/robotology/icub-firmware-models/assets/18039045/a23199e2-3276-454b-8ea1-3deb0a70c388

I tested the new `codegen` on `AMC2C` with the following current limits using the `yarprobotinterface`:

```xml
        <param name="motorNominalCurrents">     30               </param>
        <param name="motorPeakCurrents">        40               </param>
        <param name="motorOverloadCurrents">    50               </param>
```

I also tested succefully the same `codegen` w/ `AMCBLDC` using the experiment-supervisor test model.

A new PR on `icub-firmware` and `icub-firmware-build` will follow. I think we can merge this PR ✅.

cc @mfussi66 @marcoaccame @Nicogene

**Comment by mfussi66** [comment]
I'll address the change asap on the WIP version of the new architectural model.

**Pull request merged**
