### PR TITLE
Add test harness to common supervisor, fix bugs, restore C code calls

### PR DESCRIPTION
**Pull request by mfussi66**
This PR creates a test harness model embedded in the new `Supervisor.slx`, located in the `Common` project.

The model is as follows:
image

On the left we have a test sequence object, and on the right a test assessment block. The first sets the input variables, while the other verifies them according to internal rules.

This harness model allowed to discover a bug caused by the refactor in the Input Dispatcher. See the issue related to this PR for details: https://github.com/robotology/icub-firmware-models/issues/72

Finally, custom code calls are restored.

### CODE REVIEW

**Review by pattacini — CHANGES_REQUESTED** [review]
Excellent work @mfussi66 🚀 

Just a minor request:
- Would you be willing to refactor the `common/tests` dir with a further level of subdirs in order to specialize the meaning? For example, the model `pmsm` could be located under `common/tests/motor`; similar subdirs should host the other tests. Avoiding using one shared big bucket will enable us to be a bit cleaner.

**Comment by pattacini** [comment]
Remember to update the project to include the new tree.

**Comment by mfussi66** [comment]
Done! 
now there is /tests/motor/pmsm and /interactive/motion_controller.slx

**Review by pattacini — APPROVED** [review]
Thanks!

**Pull request merged**
