### PR TITLE
Streamline how initial config is set for boards, remove duplicated code replacement folders

### PR DESCRIPTION
**Pull request by mfussi66**
This PR applies to the following:
- Common
- AMCFOC
- AMCBLDC_Experimental

It introduces a function called `update_actuators_config`, stored in Common, that can be used to update the initial configuration of the motion controller (motor config, limits, pids...), and store it in the related dictionary.

The board-specific projects can use it with the following, for example:
```matlab
update_actuators_config("amcbldc.sldd", "AmcbldcInitConf", amcbldc_init_config())
```

The first argument is the target dictionary, the second argument is the desired name of the struct containing the configuration (it MUST match the name in the Simulink model), and the third is a script containing the parameters.

`amcbldc_init_config` and `amcfoc_init_config` are function scripts that contain the respective init parameters, and are placed in the respective projects.

### CODE REVIEW

**Review by pattacini — COMMENTED** [review]
I've spotted that `rtw_mutex` has been removed.
Any comment on this?

**Comment by mfussi66** [comment]
It's in the project Common. Should it be placed on a specific board project?

**Comment by pattacini** [comment]
Ok, but it was already in common? Asking because this PR doesn't provide `rtw_mutex` in common right away.

So, are you just cleaning up the specific board projects?

If my understanding is correct, that's perfectly fine 👍🏻

**Comment by mfussi66** [comment]
Yes my bad, I did not specify. The directories were duplicated everywhere, and so was the code replacement with rtw_mutex! They were already in Common, that's why it did not show up on the PR.

**Review by pattacini — APPROVED** [review]

**Pull request merged**
