### PR TITLE
Models updated to R2023b and declared `Ts_*` constants

### PR DESCRIPTION
**Pull request by pattacini**
This PR mirrors #63 but w/o the update of the project files.
Only models have been updated, singularly.

### CODE REVIEW

**Comment by pattacini** [comment]
@sgiraz 
Please, test the PR on the AMCBLDC.

**Comment by pattacini** [comment]
Draft and on hold until we'll figure out what's wrong w/ R2023b-based codegen.

**Comment by pattacini** [comment]
I'll have to update this PR to include the following new stuff:
- Enable Code Generation Report to inspect the Code Replacement Library outcomes.
- Enable Sin/Cos approximations to link against CMSIS.
- Switch the Park transforms to the use of D-alignment.

cc @Nicogene @sgiraz @mfussi66 @marcoaccame

**Comment by pattacini** [comment]
The [3 points above](https://github.com/robotology/icub-firmware-models/pull/64#issuecomment-1826830847) have been addressed.

Awaiting tests on the lego setup before merging.

cc @sgiraz @Nicogene @mfussi66

**Review by sgiraz — APPROVED** [review]
Ok @pattacini!
The code has been tested successfully on `lego-setup` with `amcbldc`.

**Comment by pattacini** [comment]
Fantastic.
Thanks!

**Pull request merged**
