### PR TITLE
AMCBLDC – Update to R2023b + Define `Ts_*` constants

### PR DESCRIPTION
**Pull request by pattacini**
This PR updates the whole AMCBLDC project to R2023b.
Also, the dictionary now contains the sample times as per:

image

These params are tunable but sample times are NOT tunable inside our models.
Therefore, codegen cannot be parametric in this respect.

As a result, to change the sample time of the FOC, one needs to change the value in the dictionary and regenerate the code. At least, now this procedure is slightly easier because all those params are localized in the dictionary.

> [!important]
Before merging, better off testing the goodness of the `codegen`

cc @Nicogene @sgiraz @mfussi66 @marcoaccame @valegagge

### CODE REVIEW

**Review by ale-git — COMMENTED** [review]
Hi @pattacini, I see that now the Ts_ControlFOC is 6E-5 s that corresponds to 50 kHz PWM, while in the previous version the rate of the inner control loop was corresponding to 82 kHz, is it right?

**Comment by pattacini** [comment]
> Hi @pattacini, I see that now the Ts_ControlFOC is 6E-5 s that corresponds to 50 kHz PWM, while in the previous version the rate of the inner control loop was corresponding to 82 kHz, is it right?

Hi @ale-git 

That screenshot did refer to a version ready to be used for the AMC board, whereby the FOC cannot run at the intended rate yet.

The AMCBLDC still makes use of the following values:

image

By the way, I turned those Simulink Parameters into Constants because, eventually, sample times cannot be tunable.

**Comment by ale-git** [comment]
I see... ok for me!

**Comment by pattacini** [comment]
@sgiraz and @marcoaccame verified that this PR is not running as expected on AMCBLDC.

This could be potentially due to the fact that I was prompted to update the entire project to the latest version of MATLAB automatically. This action, if not supervised carefully by a human in all its aspects, may be disruptive.

Never mind. Tests on AMC are not blocked as @sgiraz can generate the $`60`$ $`\mu s`$ based FW from the models in the `devel` branch, although he's gonna do that by using R2023b.

In the meanwhile, I can do the modifications proposed here yet again from scratch bypassing the project's automatic update.

**Comment by pattacini** [comment]
Closing this PR.
I'll open another one.

**Pull request closed without merging**
