### PR TITLE
Common: Add motID to event; AMCFOC: evt sorter; AMCBLDC: fix set Voltage

### PR DESCRIPTION
**Pull request by mfussi66**
This PR contributes with the following:

## Common

Adds a field called motor_id to the `ReceivedEvents` data structure, to identify the target motor. The value starts from 1 and increases by 1 for each additional motor.

>[!IMPORTANT]
> In the AMCBLDC (and consequentially, the AMC), this value is fixed to 1 and the CAN Decoder is unchanged.

**Bonus:** The initialization scripts for the motor configurations for each board have been greatly simplified, and now it's only necessary to launch `initialize_<boardname>_config.m` to store the data automatically in the board dictionary.

## AMCBLDC ( and AMC)

Removes usage of the current shift factor when setting the voltage target in open loop mode.

in the **CAN Decoder** we have 
```
msg_desired_targets.voltage = single(tmp_merged >> CAN_VOLT_REF_SHIFT) / CAN_VOLT_REF_GAIN; 
```

As per https://github.com/robotology/icub-firmware-models/pull/96#pullrequestreview-2352203018 the equivalent operation is done also in the encoder:

image

```matlab
tmp1 = bitshift(pwm_fbk, CAN_VOLT_REF_SHIFT);
tmp2 = typecast(tmp1, 'uint8');
pl(3) = tmp2(1);
pl(4) = tmp2(2);
```

## AMCFOC

Adds a simple chart that sorts events based on motor_id, before entering the motion controller:

image

Graphically, it does the following:

- The events can enter in arbitrary order, and according to the motor ID they are put in the proper column:

372823012-f6a654c2-d0dd-40e9-9f97-5ee8e6ace1b1

The implementation is simple:

image

The test video shows how it works in practice, with a simplified data struct:

https://github.com/user-attachments/assets/96178980-4307-4096-a8ad-deedf2218c84

### CODE REVIEW

**Review by pattacini — CHANGES_REQUESTED** [review]
Very nice!

As discussed F2F, we'd need to address the following 2 points:
1. Switch from a 1-based to 0-based motor ids. This is because we use C-style FSM and the CAN protocol refers to 0-based motor ids as well.
2. Fix the encoding CAN FSM too with regards to the SHIFT factor.

**Comment by mfussi66** [comment]
Good point @pattacini , the latest commit fixes the wrong indexing. I also uploaded the simple test, and here is the result.

image

image

**Comment by pattacini** [comment]
Great! Did you also fix the part on the SHIFT factor?

**Comment by mfussi66** [comment]
> Great! Did you also fix the part on the SHIFT factor?

Yep, did it in [`308495f` (#96)](https://github.com/robotology/icub-firmware-models/pull/96/commits/308495f9fae729a8adde6d0c3c3a893c637b22f4) and updated the PR message accordingly.

**Review by pattacini — APPROVED** [review]

**Pull request merged**
