### PR TITLE
Make `Vcc` an input as a new field of `SensorsData`; Disable Temperature Estimation

### PR DESCRIPTION
**Pull request by pattacini**
This PR implements #10.

We can start testing the architectural changes once @sgiraz is done with the low-level handling of the `Vcc` readings[^1].

@marcoaccame already implemented the reading of `Vcc` on the AMCBLDC board.
@sgiraz is doing the same on AMC.

> [!important]
> Clearly, the glue code now needs to pass `Vcc` as an input. Find below the related references.

```c
struct SupplyVoltage
{
  real32_T voltage;
};

struct SensorsData
{
  // position encoders
  JointPositions jointpositions;

  // motor probes
  MotorSensors motorsensors;

  // supply probes
  SupplyVoltage supplyvoltagesensors;
};
```

> [!note]
>Prior to this PR, `Vcc` was initialized to $`44`$ V as a configuration parameter.

---

@mfussi66, once the PR is merged, you'd need to update the new project consistently.

[^1]: Actually, we could go on straight away and pass Vcc as a static input for the moment.

### CODE REVIEW

**Comment by pattacini** [comment]
cc @Nicogene

**Comment by pattacini** [comment]
77f20f407a6c2118d40c99820464b09954a18843 adds the wrapping angle functionality so that FOC can now guarantee that the input electrical angle is always in the correct range [0, 2$`\pi`$] to let the CMSIS sin/cos operate as expected. This is much safer.

screenshot

> [!Warning]
>In order to generate the code, I had to enable the configuration option <blk>variable-sized signals</blk> for all the models.

@sgiraz, we can give it a run to the whole PR.
@mfussi66, we should consider this point as well to be ported to the new architectural model.

**Comment by pattacini** [comment]
a3f07fd939d528447d3a961f8a0276d5587c9198 introduces a variant subsystem approach to disable temperature estimation, which is currently unfinished. This could give us some margin on the overall FOC computation time.

Screenshot 2023-12-30 200731

Screenshot 2023-12-30 200754

By default, the variant parameter is set such that the temperature estimation is off.
The variant manager can be used to switch the functionality on/off.

**Comment by pattacini** [comment]
To settle things once for good, I've provided variants implementations of the Sin/Cos with CMSIS and STD:

Screenshot 2024-01-04 183734

**Comment by pattacini** [comment]
> [!important]
> To use the new variant features, we're required to install the [Variant Manager Adds-On](https://www.mathworks.com/help/simulink/gui/variant-manager-overview.html).

**Comment by sgiraz** [comment]
Hi @pattacini, PR Tested successfully on `lego-setup`! 👍🏻

FOC duration is about 15.5 us:

| global view | zoomed in |
|:------------:|:-------------:|
| amcbldc_after_Vcc_codegen_global_vision | amcbldc_after_Vcc_codegen |

Here are the `current` (Iq), `velocity`, and `position` at different targets in current control mode:

image

cc @marcoaccame @Nicogene

**Comment by pattacini** [comment]
Thanks heaps @sgiraz!
Merging.

**Comment by pattacini** [comment]
> Important
> 
> To use the new variant features, we're required to install the [Variant Manager Adds-On](https://www.mathworks.com/help/simulink/gui/variant-manager-overview.html).

cc @mfussi66 @valegagge @ale-git

**Comment by valegagge** [comment]
> > Important
> > To use the new variant features, we're required to install the [Variant Manager Adds-On](https://www.mathworks.com/help/simulink/gui/variant-manager-overview.html).
> 
> cc @mfussi66 @valegagge @ale-git

What do you think if we create a wiki page where all necessary adds-on are listed, so those are not used to work with the model could install all necessary stuff?

 @pattacini @sgiraz @mfussi66

**Comment by pattacini** [comment]
Yes, I took note of this request.
My idea is rather to fill in the [documentation](https://robotology.github.io/icub-firmware-models/) with the missing information.

We still have to complete the (long overdue) task of documenting our journey 😄

**Pull request merged**
